"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import Navbar from "@/components/layout/Navbar";
import { useAuth } from "@/lib/authContext";
import {
  Chrome, Zap, Leaf, Target, ShoppingBag,
  ArrowRight, Star, Globe, Copy, Check, X, LayoutDashboard,
  Package, ToggleRight, FolderOpen, Puzzle, TrendingUp,
  Shield, Sparkles,
} from "lucide-react";

// ── Config ───────────────────────────────────────────────────────────────────
const CHROME_STORE_URL: string | null = null;
const EXTENSION_ZIP_URL = "/vyridian-extension.zip";

type InstallState = "idle" | "downloading" | "guide";

// ── Data ─────────────────────────────────────────────────────────────────────
const FEATURES = [
  {
    icon: Target, color: "#00d47f",
    title: "Goal impact score",
    desc: "See exactly how many days this purchase delays your savings goals — calculated from your real profile.",
  },
  {
    icon: Leaf, color: "#8b5cf6",
    title: "Sustainability rating",
    desc: "Every product rated High, Medium, or Low using environmental lifecycle data — not guesses.",
  },
  {
    icon: ShoppingBag, color: "#4f8ef7",
    title: "Smarter alternatives",
    desc: "Claude suggests a comparable product that's more sustainable, more affordable, or both.",
  },
  {
    icon: Zap, color: "#f59e0b",
    title: "Instant analysis",
    desc: "Results appear in seconds — no page reload, no extra tabs, no waiting.",
  },
  {
    icon: Globe, color: "#06b6d4",
    title: "Works everywhere",
    desc: "Amazon, Best Buy, Walmart, Etsy — any product page with a price.",
  },
  {
    icon: Star, color: "#f04444",
    title: "Powered by Claude AI",
    desc: "Every insight generated by Anthropic's Claude — not scraped databases or static rules.",
  },
];

const HOW_IT_WORKS = [
  {
    num: "01", icon: Package, color: "#00d47f",
    title: "Get the extension",
    desc: "Click Add to Chrome. The file downloads automatically and setup takes under 2 minutes.",
  },
  {
    num: "02", icon: Shield, color: "#8b5cf6",
    title: "Link your account",
    desc: "Connect your Vyridian dashboard to unlock personalized goal impact scores built from your real budget.",
  },
  {
    num: "03", icon: Sparkles, color: "#4f8ef7",
    title: "Shop with full clarity",
    desc: "The popup appears on any product page with financial impact, sustainability rating, and a smarter alternative — instantly.",
  },
];

const SETUP_STEPS = [
  {
    icon: Package,
    label: "Download",
    title: "Your file is downloading",
    desc: "Once it finishes, unzip it. You'll get a folder called vyridian-extension — keep it somewhere easy to find.",
    extra: null,
  },
  {
    icon: ToggleRight,
    label: "Extensions",
    title: "Open Chrome Extensions",
    desc: "Copy the address below, paste it into Chrome's address bar, and press Enter. Then flip the Developer mode switch in the top-right corner.",
    extra: "address-bar",
  },
  {
    icon: FolderOpen,
    label: "Add it",
    title: "Add the folder",
    desc: "Drag the vyridian-extension folder into the Extensions page, or click Load unpacked and select it. Vyridian will appear in your toolbar.",
    extra: null,
  },
] as const;

// ── Component ─────────────────────────────────────────────────────────────────
export default function ExtensionPage() {
  const { locale } = useParams<{ locale: string }>();
  const { user } = useAuth();
  const [installState, setInstallState] = useState<InstallState>("idle");
  const [activeStep,   setActiveStep]   = useState(0);
  const [copied,       setCopied]       = useState(false);
  const modalRef = useRef<HTMLDivElement>(null);

  // Scroll-reveal
  useEffect(() => {
    const observer = new IntersectionObserver(
      entries => entries.forEach(e => { if (e.isIntersecting) e.target.classList.add("is-visible"); }),
      { threshold: 0.08, rootMargin: "0px 0px -50px 0px" }
    );
    document.querySelectorAll(".reveal").forEach(el => observer.observe(el));
    return () => observer.disconnect();
  }, []);

  // Escape closes modal
  useEffect(() => {
    if (installState !== "guide") return;
    const handler = (e: KeyboardEvent) => { if (e.key === "Escape") setInstallState("idle"); };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [installState]);

  function handleInstall() {
    if (CHROME_STORE_URL) { window.open(CHROME_STORE_URL, "_blank", "noopener"); return; }
    setInstallState("downloading");
    const a = document.createElement("a");
    a.href = EXTENSION_ZIP_URL;
    a.download = "vyridian-extension.zip";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => { setInstallState("guide"); setActiveStep(0); }, 1100);
  }

  function handleCopy() {
    navigator.clipboard.writeText("chrome://extensions").then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  }

  function handleBackdrop(e: React.MouseEvent) {
    if (modalRef.current && !modalRef.current.contains(e.target as Node)) setInstallState("idle");
  }

  const signupWithReturn = `/${locale}/signup?next=/${locale}/extension`;
  const isDownloading = installState === "downloading";
  const isGuideOpen   = installState === "guide";

  return (
    <div style={{ background: "var(--color-bg)", minHeight: "100vh" }}>
      <Navbar />

      {/* ── Setup Modal ────────────────────────────────────────────────────── */}
      {isGuideOpen && (
        <div
          onClick={handleBackdrop}
          style={{
            position: "fixed", inset: 0, zIndex: 200,
            background: "rgba(0,0,0,0.82)",
            backdropFilter: "blur(12px)",
            WebkitBackdropFilter: "blur(12px)",
            display: "flex", alignItems: "center", justifyContent: "center",
            padding: "1.5rem",
          }}
          role="dialog" aria-modal="true" aria-label="Vyridian extension setup"
        >
          <div
            ref={modalRef}
            style={{
              background: "var(--color-surface)",
              border: "1px solid var(--color-border-strong)",
              borderRadius: "var(--radius-xl)",
              width: "100%", maxWidth: "440px",
              boxShadow: "0 32px 80px rgba(0,0,0,0.9), 0 0 0 1px rgba(0,212,127,0.08)",
              overflow: "hidden",
              animation: "fadeUp 0.22s var(--ease-expo) both",
            }}
          >
            {/* Modal Header */}
            <div style={{ padding: "1.5rem 1.5rem 0", display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: "1rem" }}>
              <div style={{ display: "flex", alignItems: "center", gap: "0.625rem" }}>
                <div style={{ width: "32px", height: "32px", background: "#00d47f", borderRadius: "10px", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, boxShadow: "0 0 16px rgba(0,212,127,0.4)" }}>
                  <svg width="15" height="15" viewBox="0 0 32 32" fill="none" aria-hidden="true">
                    <path d="M8 9.5L16 22.5L24 9.5" stroke="#000" strokeWidth="3.2" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                </div>
                <div>
                  <h2 style={{ fontSize: "1.0625rem", fontWeight: 700, letterSpacing: "-0.02em", color: "var(--color-text-primary)", lineHeight: 1.2 }}>Set up Vyridian</h2>
                  <p style={{ fontSize: "0.75rem", color: "var(--color-text-muted)", marginTop: "1px" }}>Preview build · {SETUP_STEPS.length} quick steps</p>
                </div>
              </div>
              <button
                onClick={() => setInstallState("idle")}
                style={{ background: "none", border: "none", cursor: "pointer", color: "var(--color-text-muted)", padding: "0.25rem", borderRadius: "6px", lineHeight: 1, flexShrink: 0 }}
                aria-label="Close"
              >
                <X size={18} />
              </button>
            </div>

            {/* Progress tabs */}
            <div style={{ display: "flex", gap: "0.375rem", padding: "1.125rem 1.5rem 0" }}>
              {SETUP_STEPS.map((s, i) => (
                <button
                  key={i} onClick={() => setActiveStep(i)}
                  style={{ flex: 1, height: "3px", border: "none", cursor: "pointer", borderRadius: "100px", padding: 0, background: i <= activeStep ? "var(--color-accent)" : "rgba(255,255,255,0.1)", transition: "background 0.2s ease" }}
                  aria-label={`${s.label} (step ${i + 1})`}
                />
              ))}
            </div>

            {/* Step content */}
            <div style={{ padding: "1.375rem 1.5rem 1.25rem", minHeight: "148px" }}>
              {(() => {
                const step = SETUP_STEPS[activeStep];
                const StepIcon = step.icon;
                return (
                  <div>
                    <div style={{ display: "flex", alignItems: "center", gap: "0.75rem", marginBottom: "0.875rem" }}>
                      <div style={{ width: "40px", height: "40px", borderRadius: "12px", background: "var(--color-accent-subtle)", border: "1px solid var(--color-accent-dim)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                        <StepIcon size={18} style={{ color: "var(--color-accent)" }} aria-hidden />
                      </div>
                      <div>
                        <p style={{ fontSize: "0.6875rem", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.07em", color: "var(--color-text-muted)", marginBottom: "2px" }}>
                          Step {activeStep + 1} of {SETUP_STEPS.length}
                        </p>
                        <h3 style={{ fontSize: "1rem", fontWeight: 700, letterSpacing: "-0.02em", color: "var(--color-text-primary)", lineHeight: 1.25 }}>{step.title}</h3>
                      </div>
                    </div>
                    <p style={{ fontSize: "0.9rem", color: "var(--color-text-secondary)", lineHeight: 1.7 }}>{step.desc}</p>
                    {step.extra === "address-bar" && (
                      <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", background: "var(--color-bg)", border: "1px solid var(--color-border)", borderRadius: "var(--radius-md)", padding: "0.625rem 0.875rem", marginTop: "0.875rem" }}>
                        <span style={{ flex: 1, fontFamily: "monospace", fontSize: "0.875rem", color: "var(--color-accent)", userSelect: "all", letterSpacing: "0.01em" }}>chrome://extensions</span>
                        <button onClick={handleCopy} className="btn btn-sm btn-ghost" style={{ gap: "0.35rem", flexShrink: 0 }} aria-label="Copy chrome://extensions">
                          {copied ? <><Check size={13} aria-hidden /> Copied</> : <><Copy size={13} aria-hidden /> Copy</>}
                        </button>
                      </div>
                    )}
                  </div>
                );
              })()}
            </div>

            {/* Navigation */}
            <div style={{ padding: "0 1.5rem 1.5rem", display: "flex", gap: "0.625rem" }}>
              {activeStep > 0 && (
                <button onClick={() => setActiveStep(s => s - 1)} className="btn btn-secondary" style={{ flex: "0 0 auto" }}>Back</button>
              )}
              {activeStep < SETUP_STEPS.length - 1 ? (
                <button onClick={() => setActiveStep(s => s + 1)} className="btn btn-primary" style={{ flex: 1, justifyContent: "center" }}>
                  Next <ArrowRight size={15} aria-hidden />
                </button>
              ) : (
                <Link
                  href={user ? `/${locale}/dashboard` : signupWithReturn}
                  className="btn btn-primary"
                  style={{ flex: 1, justifyContent: "center" }}
                  onClick={() => setInstallState("idle")}
                >
                  {user ? "Open Dashboard" : "Connect my account"} <ArrowRight size={15} aria-hidden />
                </Link>
              )}
            </div>

            {/* Pin tip */}
            <div style={{ borderTop: "1px solid var(--color-border)", background: "var(--color-bg)", padding: "1rem 1.5rem", display: "flex", alignItems: "center", gap: "0.75rem" }}>
              <div style={{ width: "30px", height: "30px", background: "rgba(139,92,246,0.1)", border: "1px solid rgba(139,92,246,0.2)", borderRadius: "9px", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                <Puzzle size={14} style={{ color: "var(--color-purple)" }} aria-hidden />
              </div>
              <p style={{ fontSize: "0.8125rem", color: "var(--color-text-secondary)", lineHeight: 1.55 }}>
                After installing, click the <strong style={{ color: "var(--color-text-primary)" }}>puzzle piece</strong> in Chrome&apos;s toolbar and pin Vyridian to keep it one click away.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* ── Hero ───────────────────────────────────────────────────────────── */}
      <section
        className="section relative"
        style={{ paddingTop: "9rem", paddingBottom: "2rem", overflow: "hidden" }}
      >
        {/* Background radial glow */}
        <div style={{ position: "absolute", top: 0, left: "50%", transform: "translateX(-50%)", width: "900px", height: "500px", background: "radial-gradient(ellipse at 50% 30%, rgba(0,212,127,0.09) 0%, rgba(79,142,247,0.04) 40%, transparent 70%)", pointerEvents: "none" }} aria-hidden />
        <div style={{ position: "absolute", top: "120px", left: "10%", width: "300px", height: "300px", background: "radial-gradient(ellipse, rgba(139,92,246,0.06) 0%, transparent 70%)", pointerEvents: "none" }} aria-hidden />

        <div className="container mx-auto px-6 max-w-5xl relative z-10">
          <div className="flex flex-col lg:flex-row items-center gap-12 lg:gap-16">
            {/* Left: Text */}
            <div className="flex-1 text-center lg:text-left">
              <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full mb-7 badge badge-green animate-fade-up" style={{ fontSize: "0.75rem" }}>
                <Chrome size={12} aria-hidden /> Chrome Extension — Free
              </div>
              <h1 className="display-xl mb-6 animate-fade-up delay-100" style={{ color: "var(--color-text-primary)" }}>
                Your financial advisor
                <br />
                <span className="text-gradient">at the checkout</span>
              </h1>
              <p
                className="animate-fade-up delay-200"
                style={{ fontSize: "1.125rem", color: "var(--color-text-secondary)", lineHeight: 1.75, maxWidth: "520px", marginBottom: "2.25rem" }}
              >
                Vyridian analyzes any product you&apos;re viewing — showing its real impact on your financial goals, a sustainability rating, and a smarter alternative. All in one click.
              </p>

              <div className="flex flex-col sm:flex-row items-center lg:items-start justify-center lg:justify-start gap-3 animate-fade-up delay-300">
                <button
                  className="btn btn-lg btn-primary"
                  onClick={handleInstall}
                  disabled={isDownloading}
                  style={{ minWidth: "200px" }}
                >
                  {isDownloading ? (
                    <><span className="animate-spin" style={{ display: "inline-block", width: 18, height: 18, border: "2.5px solid rgba(0,0,0,0.25)", borderTopColor: "#000", borderRadius: "50%" }} aria-hidden /> Downloading…</>
                  ) : (
                    <><Chrome size={18} aria-hidden /> Add to Chrome — free</>
                  )}
                </button>
                {user ? (
                  <Link href={`/${locale}/dashboard`} className="btn btn-lg btn-secondary">
                    <LayoutDashboard size={18} aria-hidden /> Open Dashboard
                  </Link>
                ) : (
                  <Link href={`/${locale}/signup`} className="btn btn-lg btn-secondary">
                    Create free account
                  </Link>
                )}
              </div>

              {!CHROME_STORE_URL && (
                <p className="animate-fade-up delay-400" style={{ marginTop: "1.125rem", fontSize: "0.8125rem", color: "var(--color-text-muted)" }}>
                  Preview build · Chrome Web Store listing coming soon
                </p>
              )}

              {/* Trust signals */}
              <div className="flex flex-wrap items-center gap-4 mt-8 animate-fade-up delay-500 justify-center lg:justify-start">
                {[
                  { icon: Shield, label: "No data sold" },
                  { icon: Zap, label: "Under 2 min setup" },
                  { icon: Star, label: "Claude AI powered" },
                ].map(({ icon: Icon, label }) => (
                  <div key={label} style={{ display: "flex", alignItems: "center", gap: "0.375rem", fontSize: "0.8125rem", color: "var(--color-text-muted)" }}>
                    <Icon size={13} style={{ color: "var(--color-accent)" }} aria-hidden />
                    {label}
                  </div>
                ))}
              </div>
            </div>

            {/* Right: Extension popup mockup */}
            <div className="flex-shrink-0 animate-fade-up delay-200 animate-float">
              <div className="mockup-popup" style={{ width: "310px" }}>
                {/* Browser bar */}
                <div style={{ background: "#0a1118", borderBottom: "1px solid rgba(255,255,255,0.07)", padding: "10px 13px", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                  <div style={{ display: "flex", alignItems: "center", gap: "7px", fontWeight: 700, fontSize: "13px", letterSpacing: "-0.02em" }}>
                    <div style={{ width: "22px", height: "22px", background: "#00d47f", borderRadius: "7px", display: "flex", alignItems: "center", justifyContent: "center", boxShadow: "0 0 10px rgba(0,212,127,0.5)" }}>
                      <svg width="12" height="12" viewBox="0 0 32 32" fill="none" aria-hidden>
                        <path d="M8 9.5L16 22.5L24 9.5" stroke="#000" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />
                      </svg>
                    </div>
                    <span style={{ color: "#f0f4f8" }}>Vyridian</span>
                  </div>
                  <span className="badge badge-green" style={{ fontSize: "9px" }}>Live</span>
                </div>
                {/* Popup body */}
                <div style={{ padding: "13px" }}>
                  <div style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: "11px", padding: "10px 11px", marginBottom: "8px" }}>
                    <div style={{ fontSize: "9px", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.08em", color: "#48556a", marginBottom: "2px" }}>Patagonia</div>
                    <p style={{ fontWeight: 600, fontSize: "12px", color: "#f0f4f8", marginBottom: "1px" }}>Nano Puff Jacket</p>
                    <p style={{ fontSize: "9px", color: "#48556a", marginBottom: "4px" }}>Clothing</p>
                    <p style={{ fontSize: "15px", fontWeight: 800, color: "#00d47f", letterSpacing: "-0.03em" }}>$229.00</p>
                  </div>
                  <div style={{ background: "rgba(240,68,68,0.08)", border: "1px solid rgba(240,68,68,0.2)", borderRadius: "11px", padding: "10px 11px", marginBottom: "8px" }}>
                    <p style={{ fontSize: "9px", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.08em", color: "#48556a", marginBottom: "6px" }}>Goal Impact</p>
                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "6px" }}>
                      <div>
                        <div style={{ fontSize: "20px", fontWeight: 800, letterSpacing: "-0.04em", color: "#f04444", lineHeight: 1 }}>8</div>
                        <div style={{ fontSize: "9px", color: "#48556a", marginTop: "2px" }}>days delayed</div>
                      </div>
                      <div>
                        <div style={{ fontSize: "20px", fontWeight: 800, letterSpacing: "-0.04em", color: "#f0f4f8", lineHeight: 1 }}>10.3%</div>
                        <div style={{ fontSize: "9px", color: "#48556a", marginTop: "2px" }}>of surplus</div>
                      </div>
                    </div>
                  </div>
                  <div style={{ background: "rgba(0,212,127,0.06)", border: "1px solid rgba(0,212,127,0.18)", borderRadius: "11px", padding: "10px 11px", marginBottom: "8px" }}>
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "4px" }}>
                      <p style={{ fontSize: "9px", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.08em", color: "#00d47f" }}>Sustainability</p>
                      <span style={{ fontSize: "9px", fontWeight: 700, color: "#00d47f", background: "rgba(0,212,127,0.12)", border: "1px solid rgba(0,212,127,0.25)", borderRadius: "100px", padding: "1px 7px" }}>High 🌿</span>
                    </div>
                    <p style={{ fontSize: "11px", color: "#8892a4" }}>Bluesign certified materials + repair program.</p>
                  </div>
                  <div style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.07)", borderRadius: "11px", padding: "10px 11px" }}>
                    <p style={{ fontSize: "9px", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.08em", color: "#48556a", marginBottom: "4px" }}>Better Alternative</p>
                    <p style={{ fontSize: "12px", fontWeight: 700, color: "#f0f4f8" }}>REI Co-op 650 Down Jacket</p>
                    <p style={{ fontSize: "10px", color: "#00d47f", marginTop: "2px", fontWeight: 600 }}>~$149–$179 · Save ~$50</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── Demo Flow: Before vs After ─────────────────────────────────────── */}
      <section style={{ padding: "6rem 0", background: "var(--color-bg-alt)", borderTop: "1px solid var(--color-border)", borderBottom: "1px solid var(--color-border)" }}>
        <div className="container mx-auto px-6 max-w-5xl">
          <div className="text-center mb-12 reveal">
            <p className="section-label-tag"><TrendingUp size={12} aria-hidden /> Shopping intelligence</p>
            <h2 className="display-md mb-3" style={{ color: "var(--color-text-primary)" }}>The difference one click makes</h2>
            <p style={{ fontSize: "1rem", color: "var(--color-text-secondary)", maxWidth: "440px", margin: "0 auto" }}>
              See what you normally miss — and what Vyridian reveals instantly.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-5 reveal">
            {/* Before */}
            <div className="card" style={{ padding: "1.75rem", position: "relative", overflow: "hidden" }}>
              <div style={{ position: "absolute", top: "1rem", right: "1rem" }}>
                <span style={{ fontSize: "0.6875rem", fontWeight: 700, padding: "0.25rem 0.75rem", borderRadius: "100px", background: "rgba(239,68,68,0.1)", color: "#ef4444", border: "1px solid rgba(239,68,68,0.2)" }}>
                  Without Vyridian
                </span>
              </div>
              <h3 style={{ fontSize: "0.9375rem", fontWeight: 700, color: "var(--color-text-primary)", marginBottom: "1.25rem", marginTop: "0.25rem" }}>
                Shopping blind
              </h3>
              <div style={{ display: "flex", flexDirection: "column", gap: "0.75rem" }}>
                {[
                  { label: "Price", value: "$229.00", color: "var(--color-text-primary)" },
                  { label: "Goal impact", value: "❓ Unknown", color: "var(--color-text-muted)" },
                  { label: "Sustainability", value: "❓ Unknown", color: "var(--color-text-muted)" },
                  { label: "Better options", value: "❓ Unknown", color: "var(--color-text-muted)" },
                ].map(({ label, value, color }) => (
                  <div key={label} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "0.625rem 0.875rem", background: "var(--color-surface-raised)", borderRadius: "var(--radius-md)", border: "1px solid var(--color-border)" }}>
                    <span style={{ fontSize: "0.875rem", color: "var(--color-text-secondary)" }}>{label}</span>
                    <span style={{ fontSize: "0.875rem", fontWeight: 600, color }}>{value}</span>
                  </div>
                ))}
              </div>
              <p style={{ marginTop: "1.125rem", fontSize: "0.875rem", color: "var(--color-text-muted)", lineHeight: 1.6 }}>
                You see a price. You guess whether it&apos;s a good deal. You buy or don&apos;t.
              </p>
            </div>

            {/* After */}
            <div
              className="card"
              style={{ padding: "1.75rem", position: "relative", overflow: "hidden", border: "1px solid rgba(0,212,127,0.2)", boxShadow: "0 0 40px rgba(0,212,127,0.06)" }}
            >
              <div style={{ position: "absolute", top: "1rem", right: "1rem" }}>
                <span style={{ fontSize: "0.6875rem", fontWeight: 700, padding: "0.25rem 0.75rem", borderRadius: "100px", background: "rgba(0,212,127,0.1)", color: "#00d47f", border: "1px solid rgba(0,212,127,0.25)" }}>
                  With Vyridian ✓
                </span>
              </div>
              <h3 style={{ fontSize: "0.9375rem", fontWeight: 700, color: "var(--color-text-primary)", marginBottom: "1.25rem", marginTop: "0.25rem" }}>
                Shopping with clarity
              </h3>
              <div style={{ display: "flex", flexDirection: "column", gap: "0.75rem" }}>
                {[
                  { label: "Price", value: "$229.00", color: "var(--color-text-primary)" },
                  { label: "Goal impact", value: "8 days delayed", color: "#ef4444" },
                  { label: "Sustainability", value: "High 🌿", color: "#00d47f" },
                  { label: "Better option", value: "REI jacket · $50 less", color: "#4f8ef7" },
                ].map(({ label, value, color }) => (
                  <div key={label} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "0.625rem 0.875rem", background: "var(--color-surface-raised)", borderRadius: "var(--radius-md)", border: "1px solid var(--color-border)" }}>
                    <span style={{ fontSize: "0.875rem", color: "var(--color-text-secondary)" }}>{label}</span>
                    <span style={{ fontSize: "0.875rem", fontWeight: 600, color }}>{value}</span>
                  </div>
                ))}
              </div>
              <p style={{ marginTop: "1.125rem", fontSize: "0.875rem", color: "var(--color-text-secondary)", lineHeight: 1.6 }}>
                You see the full picture. You decide with confidence. Every time.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ── Feature Grid ───────────────────────────────────────────────────── */}
      <section style={{ padding: "6rem 0" }}>
        <div className="container mx-auto px-6 max-w-5xl">
          <div className="text-center mb-12 reveal">
            <p className="section-label-tag"><Zap size={12} aria-hidden /> Built-in features</p>
            <h2 className="display-md mb-3" style={{ color: "var(--color-text-primary)" }}>What the extension does</h2>
            <p style={{ fontSize: "1rem", color: "var(--color-text-secondary)", maxWidth: "420px", margin: "0 auto" }}>
              Six AI-powered features, always free, running directly in your browser.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {FEATURES.map(({ icon: Icon, color, title, desc }, i) => (
              <div
                key={title}
                className={`feature-card reveal reveal-delay-${Math.min(i + 1, 5)}`}
                style={{ position: "relative" }}
              >
                <div
                  style={{ width: "40px", height: "40px", borderRadius: "12px", background: `${color}14`, border: `1px solid ${color}28`, display: "flex", alignItems: "center", justifyContent: "center", marginBottom: "1rem" }}
                >
                  <Icon size={18} style={{ color }} aria-hidden />
                </div>
                <h3 style={{ fontWeight: 700, fontSize: "0.9375rem", letterSpacing: "-0.015em", color: "var(--color-text-primary)", marginBottom: "0.5rem" }}>
                  {title}
                </h3>
                <p style={{ fontSize: "0.875rem", color: "var(--color-text-secondary)", lineHeight: 1.65 }}>{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── How it works ────────────────────────────────────────────────────── */}
      <section style={{ padding: "2rem 0 6rem", background: "var(--color-bg-alt)", borderTop: "1px solid var(--color-border)" }}>
        <div className="container mx-auto px-6 max-w-3xl" style={{ paddingTop: "4rem" }}>
          <div className="text-center mb-12 reveal">
            <h2 className="display-md mb-3" style={{ color: "var(--color-text-primary)" }}>Set up in 3 steps</h2>
            <p style={{ fontSize: "1rem", color: "var(--color-text-secondary)", maxWidth: "400px", margin: "0 auto" }}>
              From download to your first insight in under 2 minutes.
            </p>
          </div>

          <div style={{ display: "flex", flexDirection: "column", gap: "1.25rem" }}>
            {HOW_IT_WORKS.map(({ num, icon: Icon, color, title, desc }, i) => (
              <div
                key={num}
                className={`reveal reveal-delay-${i + 1}`}
                style={{ display: "flex", alignItems: "flex-start", gap: "1.25rem", background: "var(--color-surface)", border: "1px solid var(--color-border)", borderRadius: "var(--radius-lg)", padding: "1.5rem 1.75rem", transition: "border-color 0.25s ease, box-shadow 0.25s ease" }}
                onMouseEnter={e => {
                  e.currentTarget.style.borderColor = `${color}33`;
                  e.currentTarget.style.boxShadow = `0 8px 32px rgba(0,0,0,0.25), 0 0 0 1px ${color}18`;
                }}
                onMouseLeave={e => {
                  e.currentTarget.style.borderColor = "var(--color-border)";
                  e.currentTarget.style.boxShadow = "none";
                }}
              >
                <div style={{ width: "48px", height: "48px", borderRadius: "14px", background: `${color}14`, border: `1px solid ${color}28`, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                  <Icon size={20} style={{ color }} aria-hidden />
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{ display: "flex", alignItems: "center", gap: "0.75rem", marginBottom: "0.375rem" }}>
                    <span style={{ fontSize: "0.6875rem", fontWeight: 800, color: "var(--color-text-muted)", letterSpacing: "0.06em" }}>{num}</span>
                    <h3 style={{ fontWeight: 700, fontSize: "0.9375rem", letterSpacing: "-0.015em", color: "var(--color-text-primary)" }}>{title}</h3>
                  </div>
                  <p style={{ fontSize: "0.875rem", color: "var(--color-text-secondary)", lineHeight: 1.65 }}>{desc}</p>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-10 text-center reveal">
            <button className="btn btn-primary btn-lg" onClick={handleInstall} disabled={isDownloading}>
              <Chrome size={18} aria-hidden /> Add to Chrome — it&apos;s free
            </button>
          </div>
        </div>
      </section>

      {/* ── Footer CTA ──────────────────────────────────────────────────────── */}
      <section style={{ padding: "7rem 0", background: "linear-gradient(180deg, var(--color-bg) 0%, var(--color-bg) 100%)", textAlign: "center", position: "relative", overflow: "hidden" }}>
        <div style={{ position: "absolute", top: "50%", left: "50%", transform: "translate(-50%, -50%)", width: "600px", height: "300px", background: "radial-gradient(ellipse, rgba(0,212,127,0.07) 0%, transparent 70%)", pointerEvents: "none" }} aria-hidden />
        <div className="container mx-auto px-6 max-w-xl reveal" style={{ position: "relative", zIndex: 1 }}>
          <p className="section-label-tag justify-center" style={{ justifyContent: "center" }}>
            <Star size={12} aria-hidden /> Ready to shop smarter?
          </p>
          <h2 className="display-md mb-5" style={{ color: "var(--color-text-primary)" }}>
            Every purchase is a decision.
            <br />
            <span className="text-gradient">Make it an informed one.</span>
          </h2>
          <p style={{ fontSize: "1.0625rem", color: "var(--color-text-secondary)", marginBottom: "2.5rem", lineHeight: 1.75, maxWidth: "400px", margin: "0 auto 2.5rem" }}>
            Install the extension and link your free account to unlock personalized financial insights on every product you view.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
            <button className="btn btn-lg btn-primary" onClick={handleInstall} disabled={isDownloading} style={{ minWidth: "210px" }}>
              <Chrome size={18} aria-hidden /> Add to Chrome
            </button>
            {user ? (
              <Link href={`/${locale}/dashboard`} className="btn btn-lg btn-secondary">
                <LayoutDashboard size={18} aria-hidden /> Open Dashboard
              </Link>
            ) : (
              <Link href={`/${locale}/signup`} className="btn btn-lg btn-secondary">
                Create account <ArrowRight size={18} aria-hidden />
              </Link>
            )}
          </div>
        </div>
      </section>

      <footer style={{ borderTop: "1px solid var(--color-border)", padding: "1.75rem 0" }}>
        <div className="container mx-auto px-6 text-center">
          <p style={{ fontSize: "0.8125rem", color: "var(--color-text-muted)" }}>
            Vyridian — Personal finance &amp; sustainability ·{" "}
            <Link href={`/${locale}`} style={{ color: "var(--color-accent)" }}>Back to home</Link>
          </p>
        </div>
      </footer>
    </div>
  );
}
