"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import Navbar from "@/components/layout/Navbar";
import { useAuth } from "@/lib/authContext";
import {
  Chrome, Download, Zap, Leaf, Target, ShoppingBag,
  ArrowRight, Star, Globe, Copy, Check, X, LayoutDashboard,
} from "lucide-react";

export default function ExtensionPage() {
  const { locale } = useParams<{ locale: string }>();
  const { user } = useAuth();
  const [showGuide, setShowGuide] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => entries.forEach((e) => {
        if (e.isIntersecting) e.target.classList.add("is-visible");
      }),
      { threshold: 0.08, rootMargin: "0px 0px -50px 0px" }
    );
    document.querySelectorAll(".reveal").forEach((el) => observer.observe(el));
    return () => observer.disconnect();
  }, []);

  function handleCopy() {
    navigator.clipboard.writeText("chrome://extensions").then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  const steps = [
    {
      num: "1",
      title: "Install the extension",
      desc: "Add Vyridian to Chrome using Developer mode — free, no account required to try it.",
    },
    {
      num: "2",
      title: "Set up your profile",
      desc: "Link to your Vyridian dashboard to unlock personalized goal impact scores.",
    },
    {
      num: "3",
      title: "Shop with confidence",
      desc: "The popup appears automatically on product pages with insights, ratings, and alternatives.",
    },
  ];

  const features = [
    {
      icon: Target,
      color: "#00d47f",
      title: "Goal impact score",
      desc: "See how many days this purchase delays your savings goals — in real numbers.",
    },
    {
      icon: Leaf,
      color: "#8b5cf6",
      title: "Sustainability rating",
      desc: "Every product is rated High, Medium, or Low based on its environmental profile.",
    },
    {
      icon: ShoppingBag,
      color: "#4f8ef7",
      title: "Smarter alternatives",
      desc: "Claude suggests a comparable product that's more sustainable, more affordable, or both.",
    },
    {
      icon: Zap,
      color: "#f59e0b",
      title: "Instant results",
      desc: "Analysis appears in seconds. No page reload, no extra tabs — just open and see.",
    },
    {
      icon: Globe,
      color: "#06b6d4",
      title: "Works everywhere",
      desc: "Amazon, Best Buy, Walmart — if there's a product page, it works.",
    },
    {
      icon: Star,
      color: "#f04444",
      title: "Powered by Claude AI",
      desc: "Every insight is generated by Anthropic's Claude — not scraped databases or static rules.",
    },
  ];

  const installGuideSteps = [
    <>
      Navigate to{" "}
      <code
        style={{
          background: "var(--color-bg)",
          color: "var(--color-accent)",
          padding: "1px 6px",
          borderRadius: "4px",
          fontFamily: "monospace",
          fontSize: "0.875rem",
        }}
      >
        chrome://extensions
      </code>{" "}
      and enable <strong>Developer mode</strong> (top-right toggle)
    </>,
    <>Click <strong>Load unpacked</strong></>,
    <>
      Select the{" "}
      <code style={{ background: "var(--color-bg)", color: "var(--color-accent)", padding: "1px 6px", borderRadius: "4px", fontFamily: "monospace", fontSize: "0.875rem" }}>
        /extension
      </code>{" "}
      folder from the project root
    </>,
    <>
      Click the <strong>Vyridian</strong> icon in your Chrome toolbar to get started
    </>,
  ];

  return (
    <div style={{ background: "var(--color-bg)", minHeight: "100vh" }}>
      <Navbar />

      {/* ── Hero ────────────────────────────────────────────── */}
      <section className="section relative" style={{ paddingTop: "10rem", paddingBottom: "4rem", overflow: "hidden" }}>
        {/* Background glow */}
        <div
          style={{
            position: "absolute",
            top: "0",
            left: "50%",
            transform: "translateX(-50%)",
            width: "700px",
            height: "400px",
            background: "radial-gradient(ellipse, rgba(0,212,127,0.07) 0%, transparent 70%)",
            pointerEvents: "none",
          }}
          aria-hidden="true"
        />

        <div className="container mx-auto px-6 max-w-5xl text-center relative z-10">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full mb-8 badge badge-green animate-fade-up">
            <Chrome size={12} aria-hidden />
            Chrome Extension — Free
          </div>
          <h1
            className="display-xl mb-6 animate-fade-up delay-100"
            style={{ color: "var(--color-text-primary)" }}
          >
            Smarter shopping,
            <br />
            <span className="text-gradient">at the moment it counts</span>
          </h1>
          <p
            className="animate-fade-up delay-200"
            style={{
              fontSize: "1.125rem",
              color: "var(--color-text-secondary)",
              lineHeight: "1.75",
              maxWidth: "560px",
              margin: "0 auto 2.5rem",
            }}
          >
            The Vyridian extension analyzes any product you&apos;re looking at — showing its impact
            on your financial goals, a sustainability rating, and a smarter alternative. All in one click.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-3 animate-fade-up delay-300">
            <button className="btn btn-lg btn-primary" onClick={() => setShowGuide((v) => !v)}>
              <Download size={18} aria-hidden /> Install Extension
            </button>
            {user ? (
              <Link href={`/${locale}/dashboard`} className="btn btn-lg btn-secondary">
                <LayoutDashboard size={18} aria-hidden />
                Open Dashboard
              </Link>
            ) : (
              <Link href={`/${locale}/signup`} className="btn btn-lg btn-secondary">
                Create free account
              </Link>
            )}
          </div>
        </div>
      </section>

      {/* ── Install Guide (inline collapsible) ────────────── */}
      {showGuide && (
        <section style={{ padding: "0 0 3rem" }}>
          <div className="container mx-auto px-6 max-w-2xl">
            <div
              className="card"
              style={{ padding: "2rem", position: "relative", borderColor: "var(--color-accent-dim)" }}
            >
              <button
                onClick={() => setShowGuide(false)}
                style={{
                  position: "absolute", top: "1.25rem", right: "1.25rem",
                  background: "none", border: "none", cursor: "pointer",
                  color: "var(--color-text-muted)", display: "flex", alignItems: "center", padding: "0.25rem",
                }}
                aria-label="Close install guide"
              >
                <X size={18} />
              </button>
              <h2 style={{ fontSize: "1.125rem", fontWeight: 700, letterSpacing: "-0.02em", color: "var(--color-text-primary)", marginBottom: "0.5rem" }}>
                How to install (Developer build)
              </h2>
              <p style={{ fontSize: "0.875rem", color: "var(--color-text-muted)", marginBottom: "1.5rem", lineHeight: 1.6 }}>
                This is a developer preview. A production Chrome Web Store version is coming soon.
              </p>

              {/* Copy row */}
              <div
                style={{
                  display: "flex", alignItems: "center", gap: "0.75rem",
                  background: "var(--color-bg)", border: "1px solid var(--color-border)",
                  borderRadius: "var(--radius-md)", padding: "0.75rem 1rem", marginBottom: "1.25rem",
                }}
              >
                <code style={{ flex: 1, color: "var(--color-accent)", fontFamily: "monospace", fontSize: "0.9rem" }}>
                  chrome://extensions
                </code>
                <button onClick={handleCopy} className="btn btn-sm btn-ghost" style={{ flexShrink: 0, gap: "0.4rem" }} aria-label="Copy chrome://extensions">
                  {copied ? <><Check size={14} /> Copied</> : <><Copy size={14} /> Copy</>}
                </button>
              </div>

              <div style={{ display: "flex", flexDirection: "column", gap: "0.75rem" }}>
                {installGuideSteps.map((stepContent, i) => (
                  <div key={i} className="install-guide-step">
                    <div className="install-step-num">{i + 1}</div>
                    <p style={{ fontSize: "0.9rem", color: "var(--color-text-secondary)", lineHeight: 1.6, paddingTop: "0.125rem" }}>
                      {stepContent}
                    </p>
                  </div>
                ))}
              </div>

              <div style={{ marginTop: "1.5rem", paddingTop: "1.25rem", borderTop: "1px solid var(--color-border)" }}>
                <Link
                  href={user ? `/${locale}/dashboard` : `/${locale}/signup`}
                  className="btn btn-primary"
                  style={{ width: "100%", justifyContent: "center" }}
                >
                  {user ? "Open Dashboard ↗" : "I've installed it — Set up my profile"}
                  <ArrowRight size={16} aria-hidden />
                </Link>
              </div>
            </div>
          </div>
        </section>
      )}

      {/* ── Extension popup mockup ─────────────────────────── */}
      <section style={{ padding: "3rem 0 6rem" }}>
        <div className="flex justify-center px-6">
          <div className="mockup-popup reveal animate-float">
            <div
              style={{
                background: "#111822",
                borderBottom: "1px solid rgba(255,255,255,0.07)",
                padding: "11px 14px",
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
              }}
            >
              <div style={{ display: "flex", alignItems: "center", gap: "8px", fontWeight: 700, fontSize: "13.5px", letterSpacing: "-0.02em" }}>
                <div style={{ width: "22px", height: "22px", background: "#00d47f", borderRadius: "7px", display: "flex", alignItems: "center", justifyContent: "center" }}>
                  <svg width="12" height="12" viewBox="0 0 32 32" fill="none" aria-hidden="true">
                    <path d="M8 9.5L16 22.5L24 9.5" stroke="#000" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />
                  </svg>
                </div>
                <span style={{ color: "#f0f4f8" }}>Vyridian</span>
              </div>
              <span className="badge badge-green" style={{ fontSize: "9px" }}>Live</span>
            </div>
            <div style={{ padding: "14px" }}>
              <div
                style={{
                  background: "rgba(255,255,255,0.04)",
                  border: "1px solid rgba(255,255,255,0.07)",
                  borderRadius: "12px",
                  padding: "11px 12px",
                  marginBottom: "9px",
                }}
              >
                <div style={{ fontSize: "9px", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.08em", color: "#48556a", marginBottom: "3px" }}>Patagonia</div>
                <p style={{ fontWeight: 600, fontSize: "12.5px", color: "#f0f4f8", marginBottom: "1px" }}>Nano Puff Jacket</p>
                <p style={{ fontSize: "10px", color: "#48556a", marginBottom: "5px" }}>Clothing</p>
                <p style={{ fontSize: "16px", fontWeight: 800, color: "#00d47f", letterSpacing: "-0.03em" }}>$229.00</p>
              </div>
              <div
                style={{
                  background: "rgba(240,68,68,0.07)",
                  border: "1px solid rgba(240,68,68,0.2)",
                  borderRadius: "12px",
                  padding: "11px 12px",
                  marginBottom: "9px",
                }}
              >
                <p style={{ fontSize: "9px", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.08em", color: "#48556a", marginBottom: "5px" }}>
                  Goal Impact
                </p>
                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px" }}>
                  <div>
                    <div style={{ fontSize: "20px", fontWeight: 800, letterSpacing: "-0.04em", color: "#f04444", lineHeight: 1 }}>8</div>
                    <div style={{ fontSize: "9px", color: "#48556a", marginTop: "3px" }}>days delayed</div>
                  </div>
                  <div>
                    <div style={{ fontSize: "20px", fontWeight: 800, letterSpacing: "-0.04em", color: "#f0f4f8", lineHeight: 1 }}>10.3%</div>
                    <div style={{ fontSize: "9px", color: "#48556a", marginTop: "3px" }}>of surplus</div>
                  </div>
                </div>
              </div>
              <div
                style={{
                  background: "rgba(0,212,127,0.06)",
                  border: "1px solid rgba(0,212,127,0.18)",
                  borderRadius: "12px",
                  padding: "11px 12px",
                  marginBottom: "9px",
                }}
              >
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "5px" }}>
                  <p style={{ fontSize: "9px", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.08em", color: "#00d47f" }}>Sustainability</p>
                  <span style={{ fontSize: "9px", fontWeight: 700, color: "#00d47f", background: "rgba(0,212,127,0.12)", border: "1px solid rgba(0,212,127,0.25)", borderRadius: "100px", padding: "2px 7px" }}>High 🌿</span>
                </div>
                <p style={{ fontSize: "11.5px", color: "#8892a4" }}>Bluesign certified materials, repair program.</p>
              </div>
              <div
                style={{
                  background: "rgba(255,255,255,0.03)",
                  border: "1px solid rgba(255,255,255,0.07)",
                  borderRadius: "12px",
                  padding: "11px 12px",
                }}
              >
                <p style={{ fontSize: "9px", fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.08em", color: "#48556a", marginBottom: "5px" }}>Better Alternative</p>
                <p style={{ fontSize: "12.5px", fontWeight: 700, color: "#f0f4f8" }}>REI Co-op 650 Down Jacket</p>
                <p style={{ fontSize: "10px", color: "#00d47f", marginTop: "2px", fontWeight: 600 }}>~$149–$179 · Save ~$50</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── Features marquee ───────────────────────────────── */}
      <section style={{ background: "var(--color-bg-alt)", paddingTop: "5rem", paddingBottom: "5rem" }}>
        <div className="container mx-auto px-6 max-w-5xl">
          <div className="text-center mb-12 reveal">
            <p className="section-label-tag">
              <Zap size={12} aria-hidden /> Built-in features
            </p>
            <h2 className="display-md mb-3" style={{ color: "var(--color-text-primary)" }}>
              What the extension does
            </h2>
            <p style={{ fontSize: "1rem", color: "var(--color-text-secondary)", maxWidth: "440px", margin: "0 auto" }}>
              Six AI-powered features, always free, running directly in your browser.
            </p>
          </div>
        </div>

        <div className="marquee-wrapper">
          <div className="marquee-track" aria-hidden="true">
            {[...features, ...features].map(({ icon: Icon, color, title, desc }, i) => (
              <div key={i} className="marquee-card">
                <div
                  className="w-9 h-9 rounded-xl flex items-center justify-center mb-3"
                  style={{ background: `${color}14`, border: `1px solid ${color}28` }}
                >
                  <Icon size={16} style={{ color }} aria-hidden />
                </div>
                <h3 className="font-semibold text-sm mb-1.5" style={{ color: "var(--color-text-primary)", letterSpacing: "-0.01em" }}>
                  {title}
                </h3>
                <p className="text-sm leading-relaxed" style={{ color: "var(--color-text-secondary)", lineHeight: "1.6" }}>
                  {desc}
                </p>
              </div>
            ))}
          </div>
        </div>
        <ul className="sr-only">
          {features.map(({ title, desc }) => (
            <li key={title}><strong>{title}</strong>: {desc}</li>
          ))}
        </ul>
      </section>

      {/* ── How to install ─────────────────────────────────── */}
      <section className="section">
        <div className="container mx-auto px-6 max-w-3xl">
          <div className="text-center mb-12 reveal">
            <h2 className="display-md mb-3" style={{ color: "var(--color-text-primary)" }}>
              Install in 3 steps
            </h2>
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}>
            {steps.map(({ num, title, desc }, i) => (
              <div
                key={num}
                className={`reveal reveal-delay-${i + 1}`}
                style={{
                  display: "flex",
                  alignItems: "flex-start",
                  gap: "1.25rem",
                  background: "var(--color-surface)",
                  border: "1px solid var(--color-border)",
                  borderRadius: "var(--radius-lg)",
                  padding: "1.375rem 1.625rem",
                }}
              >
                <div
                  style={{
                    width: "42px",
                    height: "42px",
                    borderRadius: "12px",
                    background: "linear-gradient(135deg, var(--color-accent), #00b870)",
                    color: "#000",
                    fontWeight: 800,
                    fontSize: "1.0625rem",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    flexShrink: 0,
                    letterSpacing: "-0.02em",
                    boxShadow: "0 4px 16px var(--color-accent-dim)",
                  }}
                >
                  {num}
                </div>
                <div>
                  <h3
                    style={{ fontWeight: 700, fontSize: "0.9375rem", letterSpacing: "-0.015em", color: "var(--color-text-primary)", marginBottom: "0.375rem" }}
                  >
                    {title}
                  </h3>
                  <p style={{ fontSize: "0.875rem", color: "var(--color-text-secondary)", lineHeight: "1.65" }}>
                    {desc}
                  </p>
                </div>
              </div>
            ))}
          </div>

          <div
            className="mt-10 reveal"
            style={{ background: "var(--color-surface)", border: "1px solid var(--color-border)", borderRadius: "var(--radius-lg)", padding: "1.5rem 2rem" }}
          >
            <p style={{ fontSize: "0.875rem", fontWeight: 600, color: "var(--color-text-secondary)", marginBottom: "0.75rem" }}>
              Manual install (Developer mode)
            </p>
            <code
              style={{
                display: "block",
                background: "var(--color-bg)",
                color: "var(--color-accent)",
                fontFamily: "monospace",
                fontSize: "0.875rem",
                padding: "0.875rem 1rem",
                borderRadius: "var(--radius-md)",
                border: "1px solid var(--color-border)",
                marginBottom: "0.75rem",
              }}
            >
              chrome://extensions → Developer mode → Load unpacked → /extension
            </code>
            <p style={{ fontSize: "0.8125rem", color: "var(--color-text-muted)" }}>
              Point Chrome at the <code style={{ color: "var(--color-accent)" }}>/extension</code> folder in the project root.
            </p>
          </div>
        </div>
      </section>

      {/* ── Footer CTA ─────────────────────────────────────── */}
      <section
        style={{
          padding: "6rem 0",
          background: "linear-gradient(180deg, var(--color-bg-alt) 0%, var(--color-bg) 100%)",
          borderTop: "1px solid var(--color-border)",
          textAlign: "center",
        }}
      >
        <div className="container mx-auto px-6 max-w-xl reveal">
          <h2 className="display-md mb-5" style={{ color: "var(--color-text-primary)" }}>
            Ready to shop smarter?
          </h2>
          <p style={{ fontSize: "1.0625rem", color: "var(--color-text-secondary)", marginBottom: "2.5rem", lineHeight: "1.75" }}>
            Install the extension and create your free account to unlock personalized insights.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
            <button
              className="btn btn-lg btn-primary"
              onClick={() => {
                setShowGuide(true);
                window.scrollTo({ top: 0, behavior: "smooth" });
              }}
            >
              <Download size={18} aria-hidden /> Install extension
            </button>
            {user ? (
              <Link href={`/${locale}/dashboard`} className="btn btn-lg btn-secondary">
                <LayoutDashboard size={18} aria-hidden />
                Open Dashboard
              </Link>
            ) : (
              <Link href={`/${locale}/signup`} className="btn btn-lg btn-secondary">
                Create account <ArrowRight size={18} aria-hidden />
              </Link>
            )}
          </div>
        </div>
      </section>

      <footer style={{ borderTop: "1px solid var(--color-border)", padding: "1.75rem 0" }}>
        <div className="container mx-auto px-6 text-center">
          <p style={{ fontSize: "0.8125rem", color: "var(--color-text-muted)" }}>
            Vyridian — Personal finance &amp; sustainability ·{" "}
            <Link href={`/${locale}`} style={{ color: "var(--color-accent)" }}>
              Back to home
            </Link>
          </p>
        </div>
      </footer>
    </div>
  );
}
